name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["feature-request"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    id: feature-description
    attributes:
      label: Describe the Feature
      description: |
        Please describe the feature you are requesting. Who will use it? |
        What purpose will it serve? |
        If you are familiar with Agile development, feel free to write this as a user story.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MammothMedia/unbound-dao/tree/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
